Repository statisticsnorway/datadoc-editor, pull requests merged in 2024-02, with the labels that each got.

#143 Move extract methods to `DaplaDatasetPathInfo`
  src/datadoc/backend/dapla_dataset_path_info.py
  src/datadoc/backend/datadoc_metadata.py
  tests/backend/test_dapla_dataset_path_info.py
  tests/backend/test_datadoc_metadata.py
  tests/conftest.py
Labels: refactoring

#145 ⬆️ Update dependencies
  poetry.lock
  src/datadoc/backend/storage_adapter.py
Labels: dependencies

#144 Add VSCode Datadoc debug config
  .vscode/launch.json
Labels: testing

#153 Read in statistic subject structure
  noxfile.py
  poetry.lock
  pyproject.toml
  src/datadoc/backend/statistic_subject_mapping.py
  tests/backend/test_statistic_subject_mapping.py
  tests/resources/statistical_subject_structure/empty.xml
  tests/resources/statistical_subject_structure/simple.xml
Labels: enhancement

#154 Add test for `_open_file`
  tests/backend/test_datadoc_metadata.py
Labels: testing

#157 Add default value DRAFT for DatasetStatus
  src/datadoc/backend/datadoc_metadata.py
  tests/backend/test_datadoc_metadata.py
  tests/utils.py
Labels: enhancement

#155 Use date format regexes for preliminary matching too
  src/datadoc/backend/dapla_dataset_path_info.py
Labels: refactoring

#177 Upgrade dependencies
  poetry.lock
  pyproject.toml
Labels: dependencies

#175 Add caching to Docker builds
  .github/workflows/docker-build.yml
Labels: ci, github_actions

#190 Release v0.6.0
  pyproject.toml
Labels: skip-changelog

#186 More test cases for dataset inputs
  tests/frontend/callbacks/test_dataset_callbacks.py
Labels: testing

#189 Add tests for accepting variable metadata
  src/datadoc/frontend/callbacks/dataset.py
  src/datadoc/frontend/callbacks/utils.py
  src/datadoc/frontend/callbacks/variables.py
  src/datadoc/frontend/fields/display_variables.py
  tests/frontend/callbacks/test_dataset_callbacks.py
  tests/frontend/callbacks/test_variables_callbacks.py
Labels: testing

#194 Use a Checkbox for DPI
  src/datadoc/frontend/components/resources_test_new_variables.py
  src/datadoc/frontend/fields/display_new_variables.py
Labels: enhancement, style
