Repository statisticsnorway/datadoc-editor, pull requests merged in 2024-03, with the labels that each got.

#193 Fix date validation for variables
  src/datadoc/frontend/callbacks/dataset.py
  src/datadoc/frontend/callbacks/utils.py
  src/datadoc/frontend/callbacks/variables.py
Labels: bug

#192 Tidy and refactor test fixtures and resources
  src/datadoc/backend/unit_types.py
  tests/backend/test_datadoc_metadata.py
  tests/backend/test_statistic_subject_mapping.py
  tests/backend/test_unit_types.py
  tests/conftest.py
  tests/resources/datasets/person_data.csv
  tests/resources/datasets/person_data_v1.parquet
  tests/resources/datasets/person_data_v1.parquet.gzip
  tests/resources/datasets/person_testdata_p2021-12-31_p2021-12-31_v1.parquet
  tests/resources/datasets/sasdata.sas7bdat
  tests/resources/inndata/befolkning/person_data_v1.parquet
  tests/resources/inndata/befolkning/person_testdata_p2021-12-31_p2021-12-31_v1__DOC.json
  tests/resources/klargjorte_data/befolkning/person_data_v1.parquet
  tests/resources/klargjorte_data/person_testdata_p2021-12-31_p2021-12-31_v1.parquet
  tests/resources/klargjorte_data/person_testdata_p2021-12-31_p2021-12-31_v1__DOC.json
  tests/resources/statistikk/befolkning/person_data_v1.parquet
  tests/resources/statistikk/befolkning/person_testdata_p2021-12-31_p2021-12-31_v1.parquet
  tests/resources/statistikk/befolkning/person_testdata_p2021-12-31_p2021-12-31_v1__DOC.json
  tests/resources/utdata/befolkning/person_data_v1.parquet
  tests/resources/utdata/befolkning/person_testdata_p2021-12-31_p2021-12-31_v1.parquet
  tests/resources/utdata/befolkning/person_testdata_p2021-12-31_p2021-12-31_v1__DOC.json
  tests/utils.py
Labels: refactoring, testing

#203 Fetch unit types items from klass
  poetry.lock
  pyproject.toml
  src/datadoc/app.py
  src/datadoc/backend/dapla_dataset_path_info.py
  src/datadoc/backend/datadoc_metadata.py
  src/datadoc/backend/dataset_parser.py
  src/datadoc/backend/model_backwards_compatibility.py
  src/datadoc/backend/unit_types.py
  src/datadoc/config.py
  src/datadoc/enums.py
  src/datadoc/frontend/callbacks/dataset.py
  src/datadoc/frontend/callbacks/register_callbacks.py
  src/datadoc/frontend/callbacks/utils.py
  src/datadoc/frontend/callbacks/variables.py
  src/datadoc/frontend/components/variables_tab.py
  src/datadoc/frontend/fields/display_base.py
  src/datadoc/frontend/fields/display_dataset.py
  src/datadoc/state.py
  tests/backend/test_dapla_dataset_path_info.py
  tests/backend/test_datadoc_metadata.py
  tests/backend/test_model_backwards_compatibility.py
  tests/backend/test_unit_types.py
  tests/conftest.py
  tests/frontend/callbacks/test_callbacks_utils.py
  tests/frontend/callbacks/test_dataset_callbacks.py
  tests/frontend/callbacks/test_variables_callbacks.py
  tests/frontend/fields/test_display_dataset.py
  tests/resources/existing_metadata_file/invalid_id_field/person_data_v1__DOC.json
  tests/resources/existing_metadata_file/person_data_v1__DOC.json
  tests/resources/existing_metadata_file/valid_id_field/person_data_v1__DOC.json
  tests/resources/klargjorte_data/person_testdata_p2021-12-31_p2021-12-31_v1__DOC.json
  tests/resources/unit_types/no_code.csv
  tests/resources/unit_types/unit_types_en.csv
  tests/resources/unit_types/unit_types_nb.csv
  tests/resources/unit_types/unit_types_nn.csv
  tests/test_smoke.py
Labels: enhancement

#204 Display existing values in the frontend
  poetry.lock
  pyproject.toml
  src/datadoc/frontend/callbacks/dataset.py
  src/datadoc/frontend/callbacks/register_callbacks.py
  src/datadoc/frontend/callbacks/utils.py
  src/datadoc/frontend/callbacks/variables.py
  src/datadoc/frontend/components/resources_test_new_variables.py
  src/datadoc/frontend/fields/display_base.py
  src/datadoc/frontend/fields/display_new_variables.py
  tests/frontend/callbacks/test_dataset_callbacks.py
Labels: enhancement

#207 Remove variables datatable interface
  pyproject.toml
  src/datadoc/app.py
  src/datadoc/assets/variables_style.css
  src/datadoc/backend/datadoc_metadata.py
  src/datadoc/config.py
  src/datadoc/frontend/callbacks/register_callbacks.py
  src/datadoc/frontend/callbacks/variables.py
  src/datadoc/frontend/components/builders.py
  src/datadoc/frontend/components/new_variables_tab.py
  src/datadoc/frontend/components/resources_test_new_variables.py
  src/datadoc/frontend/components/variables_tab.py
  src/datadoc/frontend/fields/display_base.py
  src/datadoc/frontend/fields/display_new_variables.py
  src/datadoc/frontend/fields/display_variables.py
  tests/frontend/callbacks/test_variables_callbacks.py
Labels: refactoring

#211 Update error status for both time period fields
  src/datadoc/frontend/callbacks/register_callbacks.py
  src/datadoc/frontend/callbacks/utils.py
  src/datadoc/frontend/callbacks/variables.py
  src/datadoc/frontend/components/builders.py
  src/datadoc/frontend/fields/display_base.py
  src/datadoc/frontend/fields/display_variables.py
  tests/frontend/callbacks/test_variables_callbacks.py
Labels: bug

#213 Populate variables information text
  src/datadoc/frontend/callbacks/register_callbacks.py
  src/datadoc/frontend/components/builders.py
  src/datadoc/frontend/components/variables_tab.py
Labels: enhancement

#214 Release v0.8.0
  pyproject.toml
Labels: skip-changelog

#215 Run CI only against target environments
  .github/workflows/docker-build.yml
  .github/workflows/tests.yml
  .pre-commit-config.yaml
  Dockerfile
  noxfile.py
Labels: ci, performance

#222 Use a with block for ThreadPoolExecutor
  src/datadoc/backend/external_sources/external_sources.py
  src/datadoc/backend/statistic_subject_mapping.py
Labels: bug

#227 Filter out columns called __index_level_0__
  src/datadoc/backend/dataset_parser.py
  tests/backend/test_dataset_parser.py
Labels: bug
