Repository statisticsnorway/datadoc-editor, pull requests merged in 2024-04, with the labels that each got.

#270 Use correct value for dataset short_name
  src/datadoc/backend/dapla_dataset_path_info.py
  src/datadoc/backend/datadoc_metadata.py
  tests/backend/test_datadoc_metadata.py
Labels: bug

#272 Filter displayed variables by short name
  src/datadoc/frontend/callbacks/register_callbacks.py
  src/datadoc/frontend/callbacks/variables.py
  src/datadoc/frontend/components/variables_tab.py
  tests/frontend/callbacks/test_variables_callbacks.py
Labels: enhancement

#274 Save file path to correct field
  src/datadoc/backend/datadoc_metadata.py
  src/datadoc/frontend/fields/display_dataset.py
  tests/backend/test_datadoc_metadata.py
Labels: bug

#273 Add new checkbox with glossary
  poetry.lock
  src/datadoc/assets/workspace_style.css
  src/datadoc/frontend/fields/display_base.py
  src/datadoc/frontend/fields/display_variables.py
  tests/frontend/components/test_build_input_section.py
Labels: enhancement

#275 Release v0.9.0
  pyproject.toml
Labels: skip-changelog

#279 Style readonly fields
  src/datadoc/assets/input_style.css
  src/datadoc/assets/workspace_style.css
Labels: style

#283 Fix value refresh in dataset workspace
  src/datadoc/frontend/callbacks/register_callbacks.py
  src/datadoc/frontend/components/control_bars.py
  src/datadoc/frontend/fields/display_base.py
Labels: bug

#281 Deploy to NAIS on PR
  .github/workflows/integration-test.yml
  .nais/staging-pr.yaml
  Dockerfile
Labels: ci

#289 Update ssb-dash-components 0.7.2
  poetry.lock
Labels: dependencies

#290 Style dropdown glossary
  src/datadoc/assets/input_style.css
Labels: style

#292 Hover width dropdown glossary
  src/datadoc/assets/input_style.css
Labels: style

#291 Update to latest datadoc model
  poetry.lock
  pyproject.toml
  src/datadoc/backend/dapla_dataset_path_info.py
  src/datadoc/backend/datadoc_metadata.py
  src/datadoc/backend/dataset_parser.py
  src/datadoc/backend/model_backwards_compatibility.py
  src/datadoc/enums.py
  src/datadoc/frontend/callbacks/utils.py
  src/datadoc/frontend/fields/display_base.py
  src/datadoc/frontend/fields/display_dataset.py
  src/datadoc/frontend/fields/display_variables.py
  src/datadoc/utils.py
  tests/backend/test_datadoc_metadata.py
  tests/backend/test_dataset_parser.py
  tests/backend/test_model_backwards_compatibility.py
  tests/conftest.py
  tests/frontend/callbacks/test_callbacks_utils.py
  tests/frontend/callbacks/test_dataset_callbacks.py
  tests/frontend/callbacks/test_variables_callbacks.py
  tests/frontend/components/test_build_dataset_edit_section.py
  tests/resources/existing_metadata_file/compatibility/v2_2_0/person_data_v1__DOC.json
  tests/test_model.py
  tests/test_utils.py
Labels: enhancement

#293 Release v0.10.0
  pyproject.toml
Labels: skip-changelog

#295 End to end test
  .nais/staging-pr.yaml
  poetry.lock
  pyproject.toml
Labels: testing

#297 Fixes, refactoring, clean up dead code
  src/datadoc/app.py
  src/datadoc/frontend/callbacks/dataset.py
  src/datadoc/frontend/callbacks/utils.py
  src/datadoc/frontend/components/alerts.py
  src/datadoc/frontend/components/builders.py
  src/datadoc/frontend/fields/display_base.py
  src/datadoc/frontend/fields/display_dataset.py
  src/datadoc/frontend/fields/display_variables.py
  tests/frontend/callbacks/test_callbacks_utils.py
  tests/frontend/callbacks/test_dataset_callbacks.py
  tests/frontend/components/test_build_dataset_edit_section.py
Labels: bug, refactoring

#298 Tidy logging
  src/datadoc/backend/datadoc_metadata.py
  src/datadoc/config.py
  src/datadoc/frontend/callbacks/dataset.py
  src/datadoc/frontend/callbacks/utils.py
  src/datadoc/frontend/callbacks/variables.py
  src/datadoc/frontend/fields/display_base.py
  src/datadoc/logging_configuration/logging_config.py
Labels: refactoring

#300 Correct positioning of fields
  src/datadoc/frontend/fields/display_dataset.py
  tests/backend/test_datadoc_metadata.py
  tests/frontend/components/test_build_dataset_edit_section.py
Labels: bug

#299 Remove language dropdown
  src/datadoc/app.py
  src/datadoc/backend/datadoc_metadata.py
  src/datadoc/backend/dataset_parser.py
  src/datadoc/frontend/callbacks/dataset.py
  src/datadoc/frontend/callbacks/register_callbacks.py
  src/datadoc/frontend/callbacks/utils.py
  src/datadoc/frontend/callbacks/variables.py
  src/datadoc/frontend/components/builders.py
  src/datadoc/frontend/components/control_bars.py
  src/datadoc/frontend/fields/display_base.py
  src/datadoc/frontend/fields/display_dataset.py
  src/datadoc/frontend/fields/display_variables.py
  src/datadoc/state.py
  src/datadoc/utils.py
  tests/backend/test_dataset_parser.py
  tests/conftest.py
  tests/frontend/callbacks/test_callbacks_utils.py
  tests/frontend/callbacks/test_dataset_callbacks.py
  tests/frontend/callbacks/test_variables_callbacks.py
  tests/frontend/components/test_build_dataset_edit_section.py
  tests/frontend/components/test_build_edit_section.py
  tests/frontend/components/test_build_input_section.py
  tests/frontend/fields/test_display_dataset.py
  tests/test_utils.py
Labels: enhancement, refactoring

#303 Only open a dataset on button press
  src/datadoc/frontend/callbacks/register_callbacks.py
Labels: skip-changelog

#302 remove unused colour variables
  src/datadoc/frontend/components/control_bars.py
Labels: skip-changelog

#310 Improve error messages
  src/datadoc/app.py
  src/datadoc/frontend/callbacks/dataset.py
  src/datadoc/frontend/callbacks/register_callbacks.py
  src/datadoc/frontend/callbacks/variables.py
  src/datadoc/frontend/components/alerts.py
  src/datadoc/frontend/components/builders.py
  src/datadoc/frontend/fields/display_base.py
  src/datadoc/frontend/fields/display_dataset.py
  src/datadoc/frontend/fields/display_variables.py
  src/datadoc/frontend/text.py
  tests/frontend/callbacks/test_dataset_callbacks.py
  tests/frontend/callbacks/test_variables_callbacks.py
Labels: enhancement

#323 Update the type of contains_data_* fields
  poetry.lock
  pyproject.toml
  src/datadoc/backend/datadoc_metadata.py
  src/datadoc/backend/model_backwards_compatibility.py
  src/datadoc/frontend/callbacks/dataset.py
  tests/backend/test_datadoc_metadata.py
  tests/backend/test_model_backwards_compatibility.py
  tests/frontend/callbacks/test_variables_callbacks.py
  tests/resources/existing_metadata_file/compatibility/v3_2_0/person_data_v1__DOC.json
Labels: bug
