Repository statisticsnorway/datadoc-editor, pull requests merged in 2024-07, with the labels that each got.

#372 Add and improve docstrings
  src/datadoc/backend/code_list.py
  src/datadoc/backend/core.py
  src/datadoc/backend/dapla_dataset_path_info.py
  src/datadoc/backend/external_sources/external_sources.py
  src/datadoc/backend/model_backwards_compatibility.py
  src/datadoc/backend/model_validation.py
  src/datadoc/backend/utils.py
Labels: documentation

#373 Merge variables
  src/datadoc/backend/constants.py
  src/datadoc/backend/core.py
  tests/backend/test_datadoc_metadata.py
  tests/conftest.py
  tests/resources/datasets/fewer_variables_p2021-12-31_p2021-12-31_v1.parquet
  tests/resources/existing_metadata_file/fewer_variables_p2020-12-31_p2020-12-31_v1__DOC.json
  tests/resources/existing_metadata_file/person_testdata_p2020-12-31_p2020-12-31_v1__DOC.json
  tests/utils.py
Labels: enhancement

#375 Run one warning for variables
  src/datadoc/backend/core.py
  src/datadoc/backend/model_validation.py
  src/datadoc/backend/utils.py
  tests/backend/test_validators.py
Labels: refactoring
