Repository statisticsnorway/datadoc-editor, pull requests merged in 2024-05, with the labels that each got.

#332 Added klass to backstage documentation
  backstage.yaml
Labels: documentation

#335 Update backstage.yaml
  backstage.yaml
Labels: skip-changelog

#339 Refactor warning on save
  src/datadoc/config.py
  src/datadoc/constants.py
  src/datadoc/frontend/callbacks/dataset.py
  src/datadoc/frontend/callbacks/utils.py
  src/datadoc/frontend/callbacks/variables.py
Labels: refactoring

#342 Release v0.12.0
  pyproject.toml
Labels: skip-changelog
